# Generated by Django 6.0.4 on 2026-08-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="hero/")),
                ("btn_primary_text", models.CharField(blank=True, max_length=50)),
                ("btn_primary_url", models.CharField(blank=True, max_length=200)),
                ("btn_secondary_text", models.CharField(blank=True, max_length=50)),
                ("btn_secondary_url", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
