# Generated by Django 6.0.4 on 2026-08-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_heroslide"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=100)),
                ("prezime", models.CharField(max_length=100)),
                ("telefon", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("adresa", models.TextField()),
                ("napomena", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nova", "Nova"),
                            ("u_obradi", "U obradi"),
                            ("isporucena", "Isporučena"),
                            ("otkazana", "Otkazana"),
                        ],
                        default="nova",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=200)),
                ("cijena", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kolicina", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stavke",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
