# Generated by Django 6.0.4 on 2026-09-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_order_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-date"],
                "verbose_name": "Vijest",
                "verbose_name_plural": "Vijesti",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order"],
                "verbose_name": "Kategorija",
                "verbose_name_plural": "Kategorije",
            },
        ),
        migrations.AlterModelOptions(
            name="heroslide",
            options={
                "ordering": ["order"],
                "verbose_name": "Uvodni dio",
                "verbose_name_plural": "Uvodni dio",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Narudžba", "verbose_name_plural": "Narudžbe"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Stavka narudžbe",
                "verbose_name_plural": "Stavke narudžbe",
            },
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={
                "ordering": ["order"],
                "verbose_name": "Partner",
                "verbose_name_plural": "Partneri",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Proizvod",
                "verbose_name_plural": "Proizvodi",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
